dist: bionic
language: python
python:
  - "3.6"
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-server-dev-11
before_install:
  - sudo apt-get update
  - sudo apt-get install --yes python3-setuptools python3.6-dev make gcc
  # Will clone and compile Multicorn
  - git clone git://github.com/Kozea/Multicorn.git /opt/Multicorn
  - cd /opt/Multicorn
  # - sudo sh -c "export PYTHON_OVERRIDE=python3.6 make && make install"
  - sudo mkdir -p /usr/share/doc/postgresql-doc-11 /usr/lib/postgresql/11/lib/bitcode/
  - sudo chmod 777 /usr/share/doc/postgresql-doc-11 /usr/lib/postgresql/11/lib/ /usr/share/postgresql/11/extension/ /usr/lib/postgresql/11/lib/bitcode/
  - make && make install
  # Back to bigquery_fdw's directory
  - cd -
  # Installing packages
  - pip install pycodestyle codecov
  - python3 setup.py install
before_script:
  # Decrypt BigQuery key
  - mkdir /opt/key/
  - openssl aes-256-cbc -K $encrypted_c2c405a197db_key -iv $encrypted_c2c405a197db_iv -in src/unittest/utils/key/key.json.enc -out /opt/key/key.json -d
  #- psql -c 'create database fdw;' -U postgres
  #- psql -f sample_sql/setup.sql fdw -U postgres
script:
  - pycodestyle --exclude=venv --ignore=E501 .
  - coverage run --source=. -m pytest
  - coverage report -m
after_success:
  - codecov
