name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install PostgreSQL dev
        run: |
          sudo apt update
          sudo apt search postgresql-server
          sudo apt install postgresql-server-dev-all
      - name: Clone and compile Multicorn
        run: |
          git clone git://github.com/gabfl/Multicorn.git /opt/Multicorn
          cd /opt/Multicorn
          sudo mkdir -p /usr/share/doc/postgresql-doc-14 /usr/lib/postgresql/14/lib/bitcode/
          sudo chmod 777 /usr/share/doc/postgresql-doc-14 /usr/lib/postgresql/14/lib/ /usr/share/postgresql/14/extension/ /usr/lib/postgresql/14/lib/bitcode/
          make && make install
      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          pg_isready